<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIGIAToW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIGIAToW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIGIAToW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIGIAToW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIGIAToW\App_KernelDevDebugContainer([
    'container.build_hash' => 'IGIAToW',
    'container.build_id' => '1c7d4799',
    'container.build_time' => 1770669202,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIGIAToW');
