parameters:
    env(RECAPTCHA_SITE_KEY): ''
    env(RECAPTCHA_SECRET_KEY): ''

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\PasswordResetController:
        arguments:
            $recaptchaSiteKey: '%env(RECAPTCHA_SITE_KEY)%'
            $recaptchaSecretKey: '%env(RECAPTCHA_SECRET_KEY)%'
