<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lf3Vw_JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lf3Vw.J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entitecollecte' => ['privates', '.errored..service_locator.Lf3Vw.J.App\\Entity\\Entitecollecte', NULL, 'Cannot autowire service ".service_locator.Lf3Vw.J": it needs an instance of "App\\Entity\\Entitecollecte" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'entitecollecte' => 'App\\Entity\\Entitecollecte',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.Lf3Vw.J'])) {
            return $container->privates['.service_locator.Lf3Vw.J'];
        }

        return $container->privates['.service_locator.Lf3Vw.J'] = $instance;
    }
}
