<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z5j21NCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z5j21NC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagne' => ['privates', '.errored..service_locator.Z5j21NC.App\\Entity\\Compagne', NULL, 'Cannot autowire service ".service_locator.Z5j21NC": it needs an instance of "App\\Entity\\Compagne" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'compagne' => 'App\\Entity\\Compagne',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.Z5j21NC'])) {
            return $container->privates['.service_locator.Z5j21NC'];
        }

        return $container->privates['.service_locator.Z5j21NC'] = $instance;
    }
}
