<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJn0AUbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IJn0AUb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CompagneController::index' => ['privates', '.service_locator.8ZSh0fZ.App\\Controller\\CompagneController::index()', 'getCompagneControllerindexService', true],
            'App\\Controller\\CompagneController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CompagneController::new()', 'getCompagneControllernewService', true],
            'App\\Controller\\CompagneController::show' => ['privates', '.service_locator.O.zFVtq.App\\Controller\\CompagneController::show()', 'getCompagneControllershowService', true],
            'App\\Controller\\CompagneController::edit' => ['privates', '.service_locator.Z5j21NC.App\\Controller\\CompagneController::edit()', 'getCompagneControllereditService', true],
            'App\\Controller\\CompagneController::delete' => ['privates', '.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()', 'getCompagneControllerdeleteService', true],
            'App\\Controller\\EntitecollecteController::index' => ['privates', '.service_locator.lp2bxR7.App\\Controller\\EntitecollecteController::index()', 'getEntitecollecteControllerindexService', true],
            'App\\Controller\\EntitecollecteController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\EntitecollecteController::new()', 'getEntitecollecteControllernewService', true],
            'App\\Controller\\EntitecollecteController::show' => ['privates', '.service_locator.3O4I8xy.App\\Controller\\EntitecollecteController::show()', 'getEntitecollecteControllershowService', true],
            'App\\Controller\\EntitecollecteController::edit' => ['privates', '.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()', 'getEntitecollecteControllereditService', true],
            'App\\Controller\\EntitecollecteController::delete' => ['privates', '.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::delete()', 'getEntitecollecteControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\CompagneController:index' => ['privates', '.service_locator.8ZSh0fZ.App\\Controller\\CompagneController::index()', 'getCompagneControllerindexService', true],
            'App\\Controller\\CompagneController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\CompagneController::new()', 'getCompagneControllernewService', true],
            'App\\Controller\\CompagneController:show' => ['privates', '.service_locator.O.zFVtq.App\\Controller\\CompagneController::show()', 'getCompagneControllershowService', true],
            'App\\Controller\\CompagneController:edit' => ['privates', '.service_locator.Z5j21NC.App\\Controller\\CompagneController::edit()', 'getCompagneControllereditService', true],
            'App\\Controller\\CompagneController:delete' => ['privates', '.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()', 'getCompagneControllerdeleteService', true],
            'App\\Controller\\EntitecollecteController:index' => ['privates', '.service_locator.lp2bxR7.App\\Controller\\EntitecollecteController::index()', 'getEntitecollecteControllerindexService', true],
            'App\\Controller\\EntitecollecteController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\EntitecollecteController::new()', 'getEntitecollecteControllernewService', true],
            'App\\Controller\\EntitecollecteController:show' => ['privates', '.service_locator.3O4I8xy.App\\Controller\\EntitecollecteController::show()', 'getEntitecollecteControllershowService', true],
            'App\\Controller\\EntitecollecteController:edit' => ['privates', '.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()', 'getEntitecollecteControllereditService', true],
            'App\\Controller\\EntitecollecteController:delete' => ['privates', '.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::delete()', 'getEntitecollecteControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CompagneController::index' => '?',
            'App\\Controller\\CompagneController::new' => '?',
            'App\\Controller\\CompagneController::show' => '?',
            'App\\Controller\\CompagneController::edit' => '?',
            'App\\Controller\\CompagneController::delete' => '?',
            'App\\Controller\\EntitecollecteController::index' => '?',
            'App\\Controller\\EntitecollecteController::new' => '?',
            'App\\Controller\\EntitecollecteController::show' => '?',
            'App\\Controller\\EntitecollecteController::edit' => '?',
            'App\\Controller\\EntitecollecteController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CompagneController:index' => '?',
            'App\\Controller\\CompagneController:new' => '?',
            'App\\Controller\\CompagneController:show' => '?',
            'App\\Controller\\CompagneController:edit' => '?',
            'App\\Controller\\CompagneController:delete' => '?',
            'App\\Controller\\EntitecollecteController:index' => '?',
            'App\\Controller\\EntitecollecteController:new' => '?',
            'App\\Controller\\EntitecollecteController:show' => '?',
            'App\\Controller\\EntitecollecteController:edit' => '?',
            'App\\Controller\\EntitecollecteController:delete' => '?',
        ]);

        if (isset($container->privates['.service_locator.IJn0AUb'])) {
            return $container->privates['.service_locator.IJn0AUb'];
        }

        return $container->privates['.service_locator.IJn0AUb'] = $instance;
    }
}
