<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompagneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O.zFVtq.App\Entity\Compagne' shared service.
     *
     * @return \App\Entity\Compagne
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O.zFVtq": it needs an instance of "App\\Entity\\Compagne" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
