<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompagneControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z5j21NC.App\Controller\CompagneController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Z5j21NC'] ?? $container->load('get_ServiceLocator_Z5j21NCService'));

        if (isset($container->privates['.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()'])) {
            return $container->privates['.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\CompagneController::delete()', $container);

        if (isset($container->privates['.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()'])) {
            return $container->privates['.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()'];
        }

        return $container->privates['.service_locator.Z5j21NC.App\\Controller\\CompagneController::delete()'] = $instance;
    }
}
