<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompagneControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O.zFVtq.App\Controller\CompagneController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O.zFVtq.App\\Controller\\CompagneController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'compagne' => ['privates', '.errored..service_locator.O.zFVtq.App\\Entity\\Compagne', NULL, 'Cannot autowire service ".service_locator.O.zFVtq": it needs an instance of "App\\Entity\\Compagne" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'compagne' => 'App\\Entity\\Compagne',
        ]))->withContext('App\\Controller\\CompagneController::show()', $container);
    }
}
