<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitecollecte2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Lf3Vw.J.App\Entity\Entitecollecte' shared service.
     *
     * @return \App\Entity\Entitecollecte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Lf3Vw.J": it needs an instance of "App\\Entity\\Entitecollecte" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
