<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitecollecteControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3O4I8xy.App\Controller\EntitecollecteController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3O4I8xy.App\\Controller\\EntitecollecteController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entitecollecte' => ['privates', '.errored..service_locator.3O4I8xy.App\\Entity\\Entitecollecte', NULL, 'Cannot autowire service ".service_locator.3O4I8xy": it needs an instance of "App\\Entity\\Entitecollecte" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'entitecollecte' => 'App\\Entity\\Entitecollecte',
        ]))->withContext('App\\Controller\\EntitecollecteController::show()', $container);
    }
}
