<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitecollecteControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lf3Vw.J.App\Controller\EntitecollecteController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.Lf3Vw.J'] ?? $container->load('get_ServiceLocator_Lf3Vw_JService'));

        if (isset($container->privates['.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()'])) {
            return $container->privates['.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\EntitecollecteController::edit()', $container);

        if (isset($container->privates['.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()'])) {
            return $container->privates['.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()'];
        }

        return $container->privates['.service_locator.Lf3Vw.J.App\\Controller\\EntitecollecteController::edit()'] = $instance;
    }
}
