<?php

namespace ContainerIGIAToW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntitecollecteControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lp2bxR7.App\Controller\EntitecollecteController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lp2bxR7.App\\Controller\\EntitecollecteController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entitecollecteRepository' => ['privates', 'App\\Repository\\EntitecollecteRepository', 'getEntitecollecteRepositoryService', true],
        ], [
            'entitecollecteRepository' => 'App\\Repository\\EntitecollecteRepository',
        ]))->withContext('App\\Controller\\EntitecollecteController::index()', $container);
    }
}
