<?php

namespace App\Controller\Front;

use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use App\Service\StockAlloc;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;

class CommandeController extends AbstractController
{
  #[Route('/front/commande', name: 'front_commandes_index', methods: ['GET'])]
  public function index(CommandeRepository $commandeRepository): Response
  {
    $commandes = $commandeRepository->findBy([], ['id' => 'DESC']);

    return $this->render('Front/Commande.html.twig', [
      'commandes' => $commandes,
    ]);
  }

  #[Route('/front/new', name: 'front_commande_new', methods: ['GET', 'POST'])]
  public function new(
    Request $request,
    EntityManagerInterface $em,
    StockAlloc $alloc,
    MailerInterface $mailer,
  ): Response {
    $user = $this->getUser();
    if (!$user) {
        return $this->redirectToRoute('app_login');
    }

    // Assuming User entity has getClient method as seen in CampagneController
    /** @var \App\Entity\User $user */
    $client = $user->getClient();

    if (!$client) {
        $this->addFlash('warning', 'Vous devez compléter votre profil client pour commander.');
        return $this->redirectToRoute('front_commandes_index'); 
    }

    $commande = new Commande();
    $commande->setStatus('En Attente');
    $commande->setClient($client); // Set autogenerated client

    $form = $this->createForm(CommandeType::class, $commande);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      // Entity validation passed — now attempt stock allocation
      try {
        $alloc->assignStockOrThrow($commande);
      } catch (\RuntimeException $e) {
        $errorMsg = $e->getMessage();
        // Attach to banque if mentioned, otherwise to quantite
        if (str_contains(strtolower($errorMsg), 'banque')) {
          $form->get('banque')->addError(new FormError($errorMsg));
        } else {
          $form->get('quantite')->addError(new FormError($errorMsg));
        }
      }

      // Only persist if no stock-allocation errors were added
      if ($form->getErrors(true)->count() === 0) {
        $em->persist($commande);
        $em->flush();

        // Use logged-in user's email directly
        $toEmail = $user->getEmail();

        if (!$toEmail) {
           // Should not happen for a logged in user usually
           $this->addFlash('danger', 'Commande created but no email found.');
           return $this->redirectToRoute('front_commandes_index');
        }

        $email = (new TemplatedEmail())
          ->from(new Address('khalilboujemaa2@gmail.com', 'BloodLink'))
          ->to($toEmail)
          ->subject('Votre commande a été créée #' . $commande->getId())
          ->htmlTemplate('Email/commande.html.twig')
          ->context([
            'commande' => $commande,
            'clientName' => $user->getNom(), // Or $client->getUser()->getNom()
          ]);

        try {
          $mailer->send($email);
          $this->addFlash('success', 'Commande Créée + Email sent.');
        } catch (\Throwable $e) {
          $this->addFlash('warning', 'Commande Créée but email failed: ' . $e->getMessage());
        }

        return $this->redirectToRoute('front_commandes_index');
      }
    }

    return $this->render('Front/AjoutCommande.html.twig', [
      'form' => $form->createView(),
    ], new Response(null, $form->isSubmitted() && !$form->isValid() ? 422 : 200));
  }
}
